In [38]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [39]:
df=pd.read_csv("ncr_ride_bookings.csv")

In [40]:
df.describe(include='all')

,Date,Time,Booking ID,Booking Status,Customer ID,Vehicle Type,Pickup Location,Drop Location,Avg VTAT,Avg CTAT,...,Reason for cancelling by Customer,Cancelled Rides by Driver,Driver Cancellation Reason,Incomplete Rides,Incomplete Rides Reason,Booking Value,Ride Distance,Driver Ratings,Customer Rating,Payment Method
count,150000,150000,150000,150000,150000,150000,150000,150000,139500.000000,102000.000000,...,10500,27000.0,27000,9000.0,9000,102000.000000,102000.000000,93000.000000,93000.000000,102000
unique,365,62910,148767,5,148788,7,176,176,NaN,NaN,...,5,NaN,4,NaN,3,NaN,NaN,NaN,NaN,5
top,2024-11-16,17:44:57,"""CNR7908610""",Completed,"""CID6468528""",Auto,Khandsa,Ashram,NaN,NaN,...,Wrong Address,NaN,Customer related issue,NaN,Customer Demand,NaN,NaN,NaN,NaN,UPI
freq,462,16,3,93000,3,37419,949,936,NaN,NaN,...,2362,NaN,6837,NaN,3040,NaN,NaN,NaN,NaN,45909
mean,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,8.456352,29.149636,...,NaN,1.0,NaN,1.0,NaN,508.295912,24.637012,4.230992,4.404584,NaN
std,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3.773564,8.902577,...,NaN,0.0,NaN,0.0,NaN,395.805774,14.002138,0.436871,0.437819,NaN
min,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.000000,10.000000,...,NaN,1.0,NaN,1.0,NaN,50.000000,1.000000,3.000000,3.000000,NaN
25%,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5.300000,21.600000,...,NaN,1.0,NaN,1.0,NaN,234.000000,12.460000,4.100000,4.200000,NaN
50%,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,8.300000,28.800000,...,NaN,1.0,NaN,1.0,NaN,414.000000,23.720000,4.300000,4.500000,NaN
75%,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,11.300000,36.800000,...,NaN,1.0,NaN,1.0,NaN,689.000000,36.820000,4.600000,4.800000,NaN
max,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,20.000000,45.000000,...,NaN,1.0,NaN,1.0,NaN,4277.000000,50.000000,5.000000,5.000000,NaN

In [41]:
df.isnull().sum()

Date                                      0
Time                                      0
Booking ID                                0
Booking Status                            0
Customer ID                               0
Vehicle Type                              0
Pickup Location                           0
Drop Location                             0
Avg VTAT                              10500
Avg CTAT                              48000
Cancelled Rides by Customer          139500
Reason for cancelling by Customer    139500
Cancelled Rides by Driver            123000
Driver Cancellation Reason           123000
Incomplete Rides                     141000
Incomplete Rides Reason              141000
Booking Value                         48000
Ride Distance                         48000
Driver Ratings                        57000
Customer Rating                       57000
Payment Method                        48000
dtype: int64

In [42]:
df.head(20)

,Date,Time,Booking ID,Booking Status,Customer ID,Vehicle Type,Pickup Location,Drop Location,Avg VTAT,Avg CTAT,...,Reason for cancelling by Customer,Cancelled Rides by Driver,Driver Cancellation Reason,Incomplete Rides,Incomplete Rides Reason,Booking Value,Ride Distance,Driver Ratings,Customer Rating,Payment Method
0,2024-03-23,12:29:38,"""CNR5884300""",No Driver Found,"""CID1982111""",eBike,Palam Vihar,Jhilmil,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2024-11-29,18:01:39,"""CNR1326809""",Incomplete,"""CID4604802""",Go Sedan,Shastri Nagar,Gurgaon Sector 56,4.9,14.0,...,NaN,NaN,NaN,1.0,Vehicle Breakdown,237.0,5.73,NaN,NaN,UPI
2,2024-08-23,08:56:10,"""CNR8494506""",Completed,"""CID9202816""",Auto,Khandsa,Malviya Nagar,13.4,25.8,...,NaN,NaN,NaN,NaN,NaN,627.0,13.58,4.9,4.9,Debit Card
3,2024-10-21,17:17:25,"""CNR8906825""",Completed,"""CID2610914""",Premier Sedan,Central Secretariat,Inderlok,13.1,28.5,...,NaN,NaN,NaN,NaN,NaN,416.0,34.02,4.6,5.0,UPI
4,2024-09-16,22:08:00,"""CNR1950162""",Completed,"""CID9933542""",Bike,Ghitorni Village,Khan Market,5.3,19.6,...,NaN,NaN,NaN,NaN,NaN,737.0,48.21,4.1,4.3,UPI
5,2024-02-06,09:44:56,"""CNR4096693""",Completed,"""CID4670564""",Auto,AIIMS,Narsinghpur,5.1,18.1,...,NaN,NaN,NaN,NaN,NaN,316.0,4.85,4.1,4.6,UPI
6,2024-06-17,15:45:58,"""CNR2002539""",Completed,"""CID6800553""",Go Mini,Vaishali,Punjabi Bagh,7.1,20.4,...,NaN,NaN,NaN,NaN,NaN,640.0,41.24,4.0,4.1,UPI
7,2024-03-19,17:37:37,"""CNR6568000""",Completed,"""CID8610436""",Auto,Mayur Vihar,Cyber Hub,12.1,16.5,...,NaN,NaN,NaN,NaN,NaN,136.0,6.56,4.4,4.2,UPI
8,2024-09-14,12:49:09,"""CNR4510807""",No Driver Found,"""CID7873618""",Go Sedan,Noida Sector 62,Noida Sector 18,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,2024-12-16,19:06:48,"""CNR7721892""",Incomplete,"""CID5214275""",Auto,Rohini,Adarsh Nagar,6.1,26.0,...,NaN,NaN,NaN,1.0,Other Issue,135.0,10.36,NaN,NaN,Cash
10,2024-06-14,16:24:12,"""CNR9070334""",Completed,"""CID6680340""",Auto,Udyog Bhawan,Dwarka Sector 21,7.7,18.9,...,NaN,NaN,NaN,NaN,NaN,181.0,19.84,4.2,4.9,Cash
11,2024-09-18,08:09:38,"""CNR9551927""",No Driver Found,"""CID7568143""",Auto,Vidhan Sabha,AIIMS,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12,2024-06-25,22:44:15,"""CNR4386945""",Cancelled by Driver,"""CID5543520""",eBike,Patel Chowk,Kherki Daula Toll,4.6,NaN,...,NaN,1.0,Personal & Car related issues,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13,2024-09-11,19:29:39,"""CNR2987763""",Completed,"""CID2669710""",Go Mini,Malviya Nagar,Ghitorni Village,12.2,28.2,...,NaN,NaN,NaN,NaN,NaN,394.0,21.44,4.1,4.7,UPI
14,2024-10-18,18:28:53,"""CNR8962232""",Completed,"""CID1789354""",Go Mini,Madipur,GTB Nagar,14.0,30.9,...,NaN,NaN,NaN,NaN,NaN,836.0,39.55,4.7,4.4,UPI
15,2024-06-07,15:05:35,"""CNR2390352""",Completed,"""CID5432215""",Auto,Jama Masjid,Khan Market,8.5,36.9,...,NaN,NaN,NaN,NaN,NaN,410.0,34.76,4.0,4.9,Uber Wallet
16,2024-07-01,10:51:16,"""CNR3221338""",Completed,"""CID2581698""",Premier Sedan,IGI Airport,Madipur,5.6,27.5,...,NaN,NaN,NaN,NaN,NaN,401.0,21.97,4.9,4.3,UPI
17,2024-12-15,15:08:25,"""CNR6739317""",Cancelled by Driver,"""CID8682675""",Go Sedan,Vinobapuri,GTB Nagar,6.0,NaN,...,NaN,1.0,Customer related issue,NaN,NaN,NaN,NaN,NaN,NaN,NaN
18,2024-11-24,09:07:10,"""CNR6126048""",Cancelled by Customer,"""CID1060329""",eBike,Kashmere Gate,Anand Vihar,12.4,NaN,...,Driver is not moving towards pickup location,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
19,2024-05-24,19:53:57,"""CNR9465840""",Cancelled by Driver,"""CID9046501""",eBike,Pitampura,Rajiv Nagar,10.3,NaN,...,NaN,1.0,Customer related issue,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [43]:
df.duplicated(subset=("Customer ID")).sum()

np.int64(1212)

In [44]:
df['Booking ID'].value_counts()

Booking ID
"CNR7908610"    3
"CNR9603232"    3
"CNR3648267"    3
"CNR2726142"    3
"CNR7199036"    3
               ..
"CNR6500631"    1
"CNR2468611"    1
"CNR6358306"    1
"CNR3030099"    1
"CNR3447390"    1
Name: count, Length: 148767, dtype: int64

In [45]:
df.dtypes

Date                                     str
Time                                     str
Booking ID                               str
Booking Status                           str
Customer ID                              str
Vehicle Type                             str
Pickup Location                          str
Drop Location                            str
Avg VTAT                             float64
Avg CTAT                             float64
Cancelled Rides by Customer          float64
Reason for cancelling by Customer        str
Cancelled Rides by Driver            float64
Driver Cancellation Reason               str
Incomplete Rides                     float64
Incomplete Rides Reason                  str
Booking Value                        float64
Ride Distance                        float64
Driver Ratings                       float64
Customer Rating                      float64
Payment Method                           str
dtype: object

In [46]:
df['Date']=pd.to_datetime(df['Date'],errors='coerce',format='mixed')

In [50]:
df.dtypes

Date                                 datetime64[us]
Time                                         object
Booking ID                                      str
Booking Status                                  str
Customer ID                                     str
Vehicle Type                                    str
Pickup Location                                 str
Drop Location                                   str
Avg VTAT                                    float64
Avg CTAT                                    float64
Cancelled Rides by Customer                 float64
Reason for cancelling by Customer               str
Cancelled Rides by Driver                   float64
Driver Cancellation Reason                      str
Incomplete Rides                            float64
Incomplete Rides Reason                         str
Booking Value                               float64
Ride Distance                               float64
Driver Ratings                              float64
Customer Rating                             float64
Payment Method                                  str
dtype: object

In [48]:
df['Time']=pd.to_datetime(df['Time'],errors='coerce',format='mixed').dt.time

In [49]:
df

,Date,Time,Booking ID,Booking Status,Customer ID,Vehicle Type,Pickup Location,Drop Location,Avg VTAT,Avg CTAT,...,Reason for cancelling by Customer,Cancelled Rides by Driver,Driver Cancellation Reason,Incomplete Rides,Incomplete Rides Reason,Booking Value,Ride Distance,Driver Ratings,Customer Rating,Payment Method
0,2024-03-23,12:29:38,"""CNR5884300""",No Driver Found,"""CID1982111""",eBike,Palam Vihar,Jhilmil,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2024-11-29,18:01:39,"""CNR1326809""",Incomplete,"""CID4604802""",Go Sedan,Shastri Nagar,Gurgaon Sector 56,4.9,14.0,...,NaN,NaN,NaN,1.0,Vehicle Breakdown,237.0,5.73,NaN,NaN,UPI
2,2024-08-23,08:56:10,"""CNR8494506""",Completed,"""CID9202816""",Auto,Khandsa,Malviya Nagar,13.4,25.8,...,NaN,NaN,NaN,NaN,NaN,627.0,13.58,4.9,4.9,Debit Card
3,2024-10-21,17:17:25,"""CNR8906825""",Completed,"""CID2610914""",Premier Sedan,Central Secretariat,Inderlok,13.1,28.5,...,NaN,NaN,NaN,NaN,NaN,416.0,34.02,4.6,5.0,UPI
4,2024-09-16,22:08:00,"""CNR1950162""",Completed,"""CID9933542""",Bike,Ghitorni Village,Khan Market,5.3,19.6,...,NaN,NaN,NaN,NaN,NaN,737.0,48.21,4.1,4.3,UPI
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
149995,2024-11-11,19:34:01,"""CNR6500631""",Completed,"""CID4337371""",Go Mini,MG Road,Ghitorni,10.2,44.4,...,NaN,NaN,NaN,NaN,NaN,475.0,40.08,3.7,4.1,Uber Wallet
149996,2024-11-24,15:55:09,"""CNR2468611""",Completed,"""CID2325623""",Go Mini,Golf Course Road,Akshardham,5.1,30.8,...,NaN,NaN,NaN,NaN,NaN,1093.0,21.31,4.8,5.0,UPI
149997,2024-09-18,10:55:15,"""CNR6358306""",Completed,"""CID9925486""",Go Sedan,Satguru Ram Singh Marg,Jor Bagh,2.7,23.4,...,NaN,NaN,NaN,NaN,NaN,852.0,15.93,3.9,4.4,Cash
149998,2024-10-05,07:53:34,"""CNR3030099""",Completed,"""CID9415487""",Auto,Ghaziabad,Saidulajab,6.9,39.6,...,NaN,NaN,NaN,NaN,NaN,333.0,45.54,4.1,3.7,UPI
149999,2024-03-10,15:38:03,"""CNR3447390""",Completed,"""CID4108667""",Premier Sedan,Ashok Park Main,Gurgaon Sector 29,3.5,33.7,...,NaN,NaN,NaN,NaN,NaN,806.0,21.19,4.6,4.9,Credit Card

In [51]:
df['Avg VTAT'] = df['Avg VTAT'].fillna(df['Avg VTAT'].median())

df['Avg CTAT'] = df['Avg CTAT'].fillna(df['Avg CTAT'].median())

df['Booking Value'] = df['Booking Value'].fillna(df['Booking Value'].median())

df['Ride Distance'] = df['Ride Distance'].fillna(df['Ride Distance'].median())

df['Driver Ratings'] = df['Driver Ratings'].fillna(df['Driver Ratings'].median())

df['Customer Rating'] = df['Customer Rating'].fillna(df['Customer Rating'].median())

In [52]:
df.isnull().sum()

Date                                      0
Time                                      0
Booking ID                                0
Booking Status                            0
Customer ID                               0
Vehicle Type                              0
Pickup Location                           0
Drop Location                             0
Avg VTAT                                  0
Avg CTAT                                  0
Cancelled Rides by Customer          139500
Reason for cancelling by Customer    139500
Cancelled Rides by Driver            123000
Driver Cancellation Reason           123000
Incomplete Rides                     141000
Incomplete Rides Reason              141000
Booking Value                             0
Ride Distance                             0
Driver Ratings                            0
Customer Rating                           0
Payment Method                        48000
dtype: int64

In [53]:
df['Booking Status'].value_counts()

Booking Status
Completed                93000
Cancelled by Driver      27000
No Driver Found          10500
Cancelled by Customer    10500
Incomplete                9000
Name: count, dtype: int64

In [54]:
df['Cancelled Rides by Customer'] = df['Cancelled Rides by Customer'].fillna(0)

In [55]:
df['Cancelled Rides by Driver'] = df['Cancelled Rides by Driver'].fillna(0)

In [56]:
df['Incomplete Rides'] = df['Incomplete Rides'].fillna(0)

In [57]:
df['Reason for cancelling by Customer'] = (
    df['Reason for cancelling by Customer'].fillna('Not Applicable')
)

df['Driver Cancellation Reason'] = (
    df['Driver Cancellation Reason'].fillna('Not Applicable')
)

df['Incomplete Rides Reason'] = (
    df['Incomplete Rides Reason'].fillna('Not Applicable')
)

In [58]:
df['Payment Method'].value_counts()

Payment Method
UPI            45909
Cash           25367
Uber Wallet    12276
Credit Card    10209
Debit Card      8239
Name: count, dtype: int64

In [59]:
# df['Payment Method'] = df['Payment Method'].fillna(
#     df['Payment Method'].mode()[0]
# )

In [60]:
pd.crosstab(df['Booking Status'], df['Payment Method'].isna())

Payment Method         False
Booking Status
Cancelled by Customer  10500
Cancelled by Driver    27000
Completed              93000
Incomplete              9000
No Driver Found        10500

In [61]:
pd.crosstab(df['Booking Status'], df['Payment Method'].isna())

Payment Method         False
Booking Status
Cancelled by Customer  10500
Cancelled by Driver    27000
Completed              93000
Incomplete              9000
No Driver Found        10500

In [62]:
df.groupby('Booking Status')['Payment Method'].apply(lambda x: x.isna().sum())

Booking Status
Cancelled by Customer    0
Cancelled by Driver      0
Completed                0
Incomplete               0
No Driver Found          0
Name: Payment Method, dtype: int64

In [63]:
df['Payment Method'].value_counts(dropna=False)

Payment Method
UPI            93909
Cash           25367
Uber Wallet    12276
Credit Card    10209
Debit Card      8239
Name: count, dtype: int64

In [66]:
# Numerical columns
df['Avg VTAT'] = df['Avg VTAT'].fillna(df['Avg VTAT'].median())
df['Avg CTAT'] = df['Avg CTAT'].fillna(df['Avg CTAT'].median())
df['Booking Value'] = df['Booking Value'].fillna(df['Booking Value'].median())
df['Ride Distance'] = df['Ride Distance'].fillna(df['Ride Distance'].median())
df['Driver Ratings'] = df['Driver Ratings'].fillna(df['Driver Ratings'].median())
df['Customer Rating'] = df['Customer Rating'].fillna(df['Customer Rating'].median())

# Indicator columns
df['Cancelled Rides by Customer'] = df['Cancelled Rides by Customer'].fillna(0)
df['Cancelled Rides by Driver'] = df['Cancelled Rides by Driver'].fillna(0)
df['Incomplete Rides'] = df['Incomplete Rides'].fillna(0)

# Reason
df['Reason for cancelling by Customer'] = df['Reason for cancelling by Customer'].fillna('Not Applicable')
df['Driver Cancellation Reason'] = df['Driver Cancellation Reason'].fillna('Not Applicable')
df['Incomplete Rides Reason'] = df['Incomplete Rides Reason'].fillna('Not Applicable')

In [68]:
df.isnull().sum()

Date                                 0
Time                                 0
Booking ID                           0
Booking Status                       0
Customer ID                          0
Vehicle Type                         0
Pickup Location                      0
Drop Location                        0
Avg VTAT                             0
Avg CTAT                             0
Cancelled Rides by Customer          0
Reason for cancelling by Customer    0
Cancelled Rides by Driver            0
Driver Cancellation Reason           0
Incomplete Rides                     0
Incomplete Rides Reason              0
Booking Value                        0
Ride Distance                        0
Driver Ratings                       0
Customer Rating                      0
Payment Method                       0
dtype: int64

In [69]:
df.duplicated(subset=['Booking ID', 'Customer ID']).sum()

np.int64(0)

In [70]:
df.describe()

,Date,Avg VTAT,Avg CTAT,Cancelled Rides by Customer,Cancelled Rides by Driver,Incomplete Rides,Booking Value,Ride Distance,Driver Ratings,Customer Rating
count,150000,150000.000000,150000.000000,150000.000000,150000.000000,150000.000000,150000.000000,150000.000000,150000.000000,150000.000000
mean,2024-06-30 16:42:40.320000,8.445407,29.037753,0.070000,0.180000,0.060000,478.121220,24.343568,4.257215,4.440842
min,2024-01-01 00:00:00,2.000000,10.000000,0.000000,0.000000,0.000000,50.000000,1.000000,3.000000,3.000000
25%,2024-03-31 00:00:00,5.600000,25.000000,0.000000,0.000000,0.000000,319.750000,17.360000,4.200000,4.300000
50%,2024-07-01 00:00:00,8.300000,28.800000,0.000000,0.000000,0.000000,414.000000,23.720000,4.300000,4.500000
75%,2024-09-30 00:00:00,11.000000,32.900000,0.000000,0.000000,0.000000,521.000000,30.650000,4.300000,4.600000
max,2024-12-30 00:00:00,20.000000,45.000000,1.000000,1.000000,1.000000,4277.000000,50.000000,5.000000,5.000000
std,NaN,3.639311,7.343053,0.255148,0.384189,0.237488,329.339976,11.554362,0.345619,0.347835

In [71]:
Q1 = df['Booking Value'].quantile(0.25)
Q3 = df['Booking Value'].quantile(0.75)
IQR = Q3 - Q1

upper_limit = Q3 + 1.5 * IQR

booking_outliers = df[df['Booking Value'] > upper_limit]

booking_outliers

,Date,Time,Booking ID,Booking Status,Customer ID,Vehicle Type,Pickup Location,Drop Location,Avg VTAT,Avg CTAT,...,Reason for cancelling by Customer,Cancelled Rides by Driver,Driver Cancellation Reason,Incomplete Rides,Incomplete Rides Reason,Booking Value,Ride Distance,Driver Ratings,Customer Rating,Payment Method
14,2024-10-18,18:28:53,"""CNR8962232""",Completed,"""CID1789354""",Go Mini,Madipur,GTB Nagar,14.0,30.9,...,Not Applicable,0.0,Not Applicable,0.0,Not Applicable,836.0,39.55,4.7,4.4,UPI
29,2024-11-03,12:24:59,"""CNR8779845""",Completed,"""CID7444351""",Auto,Faridabad Sector 15,Malviya Nagar,8.9,31.1,...,Not Applicable,0.0,Not Applicable,0.0,Not Applicable,2847.0,39.21,3.1,4.6,Debit Card
42,2024-02-12,19:42:39,"""CNR4130953""",Incomplete,"""CID3196782""",Premier Sedan,Panipat,Tagore Garden,6.4,10.5,...,Not Applicable,0.0,Not Applicable,1.0,Other Issue,966.0,18.30,4.3,4.5,Debit Card
50,2024-05-04,21:26:59,"""CNR1572483""",Incomplete,"""CID6059557""",Go Mini,Rajiv Chowk,Central Secretariat,9.9,21.6,...,Not Applicable,0.0,Not Applicable,1.0,Vehicle Breakdown,1581.0,1.82,4.3,4.5,Cash
80,2024-02-10,09:17:39,"""CNR4487090""",Completed,"""CID1210782""",Premier Sedan,Lajpat Nagar,Chirag Delhi,9.6,39.1,...,Not Applicable,0.0,Not Applicable,0.0,Not Applicable,1390.0,21.79,5.0,4.9,UPI
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
149960,2024-08-10,16:19:57,"""CNR3992344""",Completed,"""CID2988625""",Auto,Sarojini Nagar,Madipur,14.9,40.6,...,Not Applicable,0.0,Not Applicable,0.0,Not Applicable,910.0,15.86,3.9,5.0,Debit Card
149966,2024-08-03,12:37:00,"""CNR2520587""",Completed,"""CID5647520""",Go Sedan,Tughlakabad,Jahangirpuri,9.3,39.6,...,Not Applicable,0.0,Not Applicable,0.0,Not Applicable,1456.0,26.60,4.9,4.4,UPI
149984,2024-01-14,15:42:15,"""CNR2761999""",Incomplete,"""CID3743304""",Go Sedan,Azadpur,Lajpat Nagar,5.9,12.8,...,Not Applicable,0.0,Not Applicable,1.0,Customer Demand,1146.0,13.96,4.3,4.5,Cash
149996,2024-11-24,15:55:09,"""CNR2468611""",Completed,"""CID2325623""",Go Mini,Golf Course Road,Akshardham,5.1,30.8,...,Not Applicable,0.0,Not Applicable,0.0,Not Applicable,1093.0,21.31,4.8,5.0,UPI
149997,2024-09-18,10:55:15,"""CNR6358306""",Completed,"""CID9925486""",Go Sedan,Satguru Ram Singh Marg,Jor Bagh,2.7,23.4,...,Not Applicable,0.0,Not Applicable,0.0,Not Applicable,852.0,15.93,3.9,4.4,Cash

In [72]:
df.nlargest(20, 'Booking Value')[
    ['Booking ID', 'Booking Status', 'Vehicle Type',
     'Ride Distance', 'Booking Value']
]

,Booking ID,Booking Status,Vehicle Type,Ride Distance,Booking Value
7450,"""CNR7954315""",Completed,Go Mini,8.66,4277.0
83506,"""CNR1798489""",Completed,Bike,11.73,4228.0
2731,"""CNR8487909""",Completed,Auto,10.11,4220.0
90418,"""CNR5182516""",Completed,Auto,4.62,4202.0
7116,"""CNR7356012""",Completed,Go Mini,25.66,4133.0
43469,"""CNR8849175""",Completed,Go Mini,36.81,4109.0
21011,"""CNR5553074""",Completed,eBike,20.85,4093.0
32935,"""CNR8715944""",Completed,Go Sedan,46.36,4088.0
117985,"""CNR7652202""",Completed,Auto,42.72,4060.0
90667,"""CNR8875064""",Completed,Go Sedan,4.97,4044.0
10040,"""CNR1017046""",Completed,Auto,32.11,4032.0
148435,"""CNR7877701""",Completed,Go Mini,47.39,4026.0
70536,"""CNR5928940""",Completed,Premier Sedan,18.02,4008.0
14636,"""CNR5245395""",Completed,Go Sedan,38.07,3985.0
23559,"""CNR3507687""",Completed,Auto,32.48,3984.0
100795,"""CNR1704323""",Completed,Premier Sedan,4.15,3978.0
15775,"""CNR4802931""",Completed,Premier Sedan,9.52,3962.0
64804,"""CNR6309807""",Completed,Premier Sedan,18.03,3942.0
94678,"""CNR3578487""",Completed,Bike,44.67,3921.0
59602,"""CNR1018014""",Completed,Go Sedan,49.26,3917.0

In [73]:
df['Booking Value per KM'] = df['Booking Value'] / df['Ride Distance']

df.nlargest(20, 'Booking Value per KM')[
    ['Booking ID', 'Booking Status', 'Vehicle Type',
     'Ride Distance', 'Booking Value', 'Booking Value per KM']
]

,Booking ID,Booking Status,Vehicle Type,Ride Distance,Booking Value,Booking Value per KM
24759,"""CNR3705367""",Incomplete,Premier Sedan,1.00,3148.0,3148.000000
51750,"""CNR8682875""",Incomplete,Go Mini,1.41,3060.0,2170.212766
121945,"""CNR3303271""",Completed,Premier Sedan,2.06,3434.0,1666.990291
100563,"""CNR9120177""",Completed,Go Sedan,2.31,3834.0,1659.740260
127717,"""CNR1834127""",Incomplete,Premier Sedan,1.29,2102.0,1629.457364
86947,"""CNR4939487""",Completed,Bike,2.38,3767.0,1582.773109
38945,"""CNR7942625""",Completed,Auto,2.35,3487.0,1483.829787
13504,"""CNR3283452""",Incomplete,Go Sedan,2.69,3554.0,1321.189591
132831,"""CNR8210349""",Incomplete,Uber XL,1.01,1325.0,1311.881188
78576,"""CNR2137752""",Incomplete,Auto,2.69,3491.0,1297.769517
90255,"""CNR9755722""",Completed,Go Mini,2.29,2894.0,1263.755459
52699,"""CNR4880201""",Incomplete,Auto,1.16,1417.0,1221.551724
96408,"""CNR7196458""",Incomplete,Bike,1.23,1469.0,1194.308943
95651,"""CNR1211560""",Incomplete,Bike,2.70,3201.0,1185.555556
37311,"""CNR9219359""",Incomplete,Bike,1.13,1272.0,1125.663717
35636,"""CNR8371202""",Incomplete,Premier Sedan,1.10,1231.0,1119.090909
42227,"""CNR3188963""",Incomplete,Go Mini,1.89,2100.0,1111.111111
29078,"""CNR2611072""",Incomplete,Auto,1.34,1483.0,1106.716418
90426,"""CNR1410859""",Completed,Premier Sedan,3.59,3825.0,1065.459610
96004,"""CNR9956539""",Completed,Premier Sedan,2.71,2849.0,1051.291513

In [74]:
df.groupby('Vehicle Type')['Booking Value'].agg(
    ['count', 'mean', 'median', 'min', 'max']
)

               count        mean  median   min     max
Vehicle Type
Auto           37419  476.979021   414.0  50.0  4220.0
Bike           22517  479.631700   414.0  50.0  4228.0
Go Mini        29806  478.007247   414.0  50.0  4277.0
Go Sedan       27141  479.806971   414.0  50.0  4088.0
Premier Sedan  18111  478.983822   414.0  50.0  4008.0
Uber XL         4449  474.103844   414.0  50.0  3703.0
eBike          10557  475.149095   414.0  50.0  4093.0

In [75]:
df.groupby('Vehicle Type')['Booking Value per KM'].agg(
    ['count', 'mean', 'median', 'min', 'max']
)

               count       mean     median       min          max
Vehicle Type
Auto           37419  31.466556  17.453626  1.020616  1483.829787
Bike           22517  31.586334  17.453626  1.018123  1582.773109
Go Mini        29806  31.247325  17.453626  1.008065  2170.212766
Go Sedan       27141  31.469858  17.453626  1.025220  1659.740260
Premier Sedan  18111  31.326574  17.453626  1.036055  3148.000000
Uber XL         4449  31.469508  17.453626  1.113445  1311.881188
eBike          10557  30.283261  17.453626  1.022659   943.529412

In [76]:
df['Booking Value'].nunique()

2566

In [77]:
df[df['Booking Value per KM'] > 500].shape

(278, 22)

In [78]:
df[df['Booking Value per KM'] > 1000].shape

(22, 22)

In [79]:
df[df['Booking Value per KM'] > 500][
    ['Booking ID', 'Booking Status', 'Vehicle Type',
     'Ride Distance', 'Booking Value', 'Booking Value per KM']
].sort_values('Booking Value per KM', ascending=False)

,Booking ID,Booking Status,Vehicle Type,Ride Distance,Booking Value,Booking Value per KM
24759,"""CNR3705367""",Incomplete,Premier Sedan,1.00,3148.0,3148.000000
51750,"""CNR8682875""",Incomplete,Go Mini,1.41,3060.0,2170.212766
121945,"""CNR3303271""",Completed,Premier Sedan,2.06,3434.0,1666.990291
100563,"""CNR9120177""",Completed,Go Sedan,2.31,3834.0,1659.740260
127717,"""CNR1834127""",Incomplete,Premier Sedan,1.29,2102.0,1629.457364
...,...,...,...,...,...,...
43876,"""CNR1719332""",Completed,Premier Sedan,2.27,1141.0,502.643172
60266,"""CNR9302969""",Completed,Bike,3.92,1968.0,502.040816
101002,"""CNR6163713""",Completed,Go Sedan,3.18,1596.0,501.886792
138333,"""CNR2052805""",Completed,Bike,3.18,1594.0,501.257862
61866,"""CNR6137514""",Incomplete,Go Sedan,1.65,827.0,501.212121